
services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - app-network
    restart: always  # Redis her kapanırsa otomatik olarak yeniden başlatılır
networks:
  app-network:
    driver: bridge
