# Generated by Django 5.0.2 on 2024-11-22 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_attendance_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_start_time', models.IntegerField(default=8)),
                ('work_end_time', models.IntegerField(default=18)),
                ('weekend_days', models.CharField(default='5,6', max_length=50)),
            ],
        ),
    ]
