# Generated by Django 5.1.3 on 2024-11-23 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_employee'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
