# Generated by Django 5.0.2 on 2024-11-23 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_employee'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
